deployment:
  replicas: 2

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

providers:
  kubernetesIngress:
    enabled: true

service:
  type: LoadBalancer

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    http:
      tls:
        enabled: true

logs:
  general:
    level: INFO

ingressRoute:
  dashboard:
    enabled: false

additionalArguments:
  - "--api.dashboard=true"