apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/jannikseus/gitops-homelab.git
        revision: main
        directories:
          - path: apps/*/*
            exclude: true
          - path: apps/prod/portfolio
  template:
    metadata:
      name: '{{ index .path.segments 2 }}-{{ index .path.segments 1 }}'
    spec:
      project: platform
      source:
        repoURL: https://github.com/jannikseus/gitops-homelab.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PruneLast=true
