apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-image-updater
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argocd-image-updater
      targetRevision: 1.1.4
      helm:
        releaseName: argocd-image-updater
        valueFiles:
          - $values/infra/prod/argocd-image-updater/values.yaml
    - repoURL: https://github.com/jannikseus/gitops-homelab.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true

