apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/jannikseus/gitops-homelab.git
    targetRevision: main
    path: infra/prod/cert-manager-config
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - PruneLast=true