apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-prod
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: portfolio=ghcr.io/jannikseus/portfolio
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/portfolio.update-strategy: semver
    argocd-image-updater.argoproj.io/portfolio.allow-tags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+$
spec:
  project: platform
  source:
    repoURL: https://github.com/jannikseus/gitops-homelab.git
    targetRevision: main
    path: apps/prod/portfolio
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true

