apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n

  sources:
    - repoURL: ghcr.io/n8n-io/n8n-helm-chart
      chart: n8n
      targetRevision: 1.3.0
      path: .
      helm:
        releaseName: n8n
        valueFiles:
          - $values/apps/prod/n8n/values.yaml

    - repoURL: https://github.com/jannikseus/gitops-homelab.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true