queueMode:
  enabled: false

database:
  type: sqlite
  useExternal: false

redis:
  enabled: false
  useExternal: false

secretRefs:
  existingSecret: n8n-secrets

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: n8n.jannikseus.tech
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: n8n-tls
      hosts:
        - n8n.jannikseus.tech

persistence:
  enabled: true
  size: 8Gi

replicaCount: 1

resources:
  main:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi